
package com.demo.my;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MyService", targetNamespace = "http://api.webservice.demo.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MyService {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.demo.my.Response
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "query", targetNamespace = "http://api.webservice.demo.com/", className = "com.demo.my.Query")
    @ResponseWrapper(localName = "queryResponse", targetNamespace = "http://api.webservice.demo.com/", className = "com.demo.my.QueryResponse")
    public Response query(
        @WebParam(name = "arg0", targetNamespace = "")
        Request arg0);

}
